import { DefaultTheme } from 'react-native-paper';
import colors from './colors';

export const lightTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: colors.primary,
    onPrimary: '#FFFFFF',
    primaryContainer: colors.primaryContainer,
    onPrimaryContainer: colors.primaryDark,
    secondary: colors.secondary,
    onSecondary: '#172033',
    secondaryContainer: colors.secondaryContainer,
    onSecondaryContainer: colors.secondaryDark,
    background: colors.background,
    onBackground: colors.onSurface,
    surface: colors.surface,
    surfaceVariant: colors.surfaceVariant,
    onSurface: colors.onSurface,
    onSurfaceVariant: colors.onSurfaceVariant,
    error: colors.danger,
    errorContainer: colors.dangerLight,
    onErrorContainer: '#7B1F16',
    outline: colors.border,
    outlineVariant: colors.borderVariant,
    elevation: {
      level0: 'transparent',
      level1: '#FFFFFF',
      level2: '#F8FAFC',
      level3: '#F3F6FA',
      level4: '#EEF3F8',
      level5: '#E7EDF4',
    },
  },
  dark: false,
};

export const darkTheme = {
  ...DefaultTheme,
  dark: true,
  mode: 'adaptive',
  colors: {
    ...DefaultTheme.colors,
    primary: colors.primaryLight,
    primaryContainer: colors.primaryDark,
    onPrimary: '#06101F',
    onPrimaryContainer: '#DCEBFF',
    secondary: colors.secondaryLight,
    secondaryContainer: colors.secondary,
    onSecondary: '#172033',
    onSecondaryContainer: '#FFF8D8',
    background: colors.dark.background,
    onBackground: colors.dark.onSurface,
    surface: colors.dark.surface,
    surfaceVariant: colors.dark.surfaceVariant,
    onSurface: colors.dark.onSurface,
    onSurfaceVariant: colors.dark.onSurfaceVariant,
    error: colors.dangerLight,
    errorContainer: '#5B1D18',
    onErrorContainer: '#FADAD5',
    outline: colors.dark.border,
    outlineVariant: colors.dark.borderVariant,
    elevation: {
      level0: 'transparent',
      level1: '#101827',
      level2: '#17233A',
      level3: '#1D2A43',
      level4: '#25324A',
      level5: '#2E3C56',
    },
  },
};
